*! build_codebook.do
*! Append the downloaded TAPR subset and build a cross-time data dictionary.
*!
*! Reads the staging directory written by prep_stata.py, imports each
*! year x level x dataset file with the right header row and string-typed
*! identifiers, saves per-wave .dta files, then runs -datadictionary- in files
*! mode so every variable gets a per-wave row and a `changed` flag.
*!
*! Run:  stata-mp -b do build_codebook.do
*! or:   do build_codebook.do

version 16.0
clear all
set more off
set maxvar 20000                  // TAPR STAAR files reach ~4,300 columns
capture log close _all

local STAGE  "stata_stage"        // written by prep_stata.py
local BUILD  "stata_build"        // per-wave .dta land here
local DOCS   "stata_docs"         // codebooks and drift reports

capture mkdir "`BUILD'"
capture mkdir "`DOCS'"
log using "`DOCS'/build_codebook.log", replace text

* Fail with instructions, not r(601), when run before the upstream steps.
* On a fresh clone the data directories do not exist yet.
capture confirm file "`STAGE'/index.csv"
if _rc {
    di as err "`STAGE'/index.csv not found -- nothing has been staged."
    di as err "Run the upstream steps first:"
    di as err "  python3 tapr_download.py --years 2013-2025 --levels C D"
    di as err "  python3 fetch_dictionaries.py --years 2013-2025"
    di as err "  python3 prep_stata.py --input tapr_data --output `STAGE'"
    log close
    exit 601
}

di as txt _n "{hline 78}"
di as txt "TAPR codebook build   " c(current_date) " " c(current_time)
di as txt "Stata " c(stata_version) " " c(flavor) ", maxvar " c(maxvar)
di as txt "{hline 78}"

* ---------------------------------------------------------------------------
* 0. Columns that must stay STRING.
*    Two sources, and both are needed.
*    (a) A fixed list of the obvious identifier and name columns.
*    (b) string_vars from the staging index, which prep_stata.py derives from
*        the DATA: any column holding a leading-zero numeric ("001902", "07") is
*        a zero-padded code. Content detection is what catches PAIRCAMP, which a
*        name list misses -- and PAIRCAMP is precisely the variable that made
*        `append` fail with "paircamp is long in master but str10 in using data",
*        because it destrung to numeric in some years and stayed string in
*        others.
* ---------------------------------------------------------------------------
local IDVARS campus campname district distname county cntyname region regnname sumlev pairname

* ---------------------------------------------------------------------------
* 1. Read the staging index
* ---------------------------------------------------------------------------
import delimited using "`STAGE'/index.csv", varnames(1) case(lower) clear
tempfile idx
save `idx'
count
local NFILES = r(N)
di as txt _n "staged files: `NFILES'"

* ---------------------------------------------------------------------------
* 2. Import each file -> per-wave .dta
*    Everything is read as string first, then measures are destrung one at a
*    time. `capture` matters: a variable that will not destring (rating letters,
*    "Meets Requirements") is meant to stay string, not to stop the build.
* ---------------------------------------------------------------------------
di as txt _n "{hline 78}"
di as txt "IMPORT"
di as txt "{hline 78}"

local nimported 0
forvalues i = 1/`NFILES' {
    use `idx' in `i', clear
    local f    = file
    local yr   = year
    local lv   = level
    local ds   = dataset
    local nhdr = n_header_rows
    local hasl = has_labels
    local strv = string_vars

    * row 1 holds human labels only on the wizard route; prep_stata.py already
    * moved variable names to row 1 of the staged file, so varnames(1) is right
    * in both cases and `hasl` only tells us whether labels exist to attach.
    import delimited using "`STAGE'/`f'", varnames(1) case(lower) ///
        stringcols(_all) clear

    quietly ds
    local allvars `r(varlist)'
    local keepstr : list IDVARS | strv
    foreach v of local allvars {
        local isid : list posof "`v'" in keepstr
        if !`isid' capture destring `v', replace
    }

    * Apply TEA's own label text for this year, generated by prep_stata.py from
    * the per-year data dictionaries. This is what lets -datadictionary- detect
    * a label that was REWORDED between years, rather than only added/dropped.
    capture confirm file "`STAGE'/labels_`ds'_`lv'_`yr'.do"
    if !_rc quietly do "`STAGE'/labels_`ds'_`lv'_`yr'.do"

    quietly gen int  year  = `yr'
    quietly gen str1 level = "`lv'"
    quietly gen str12 dataset = "`ds'"
    label var year    "TAPR year (ccyy = spring year; 2025 = SY 2024-25)"
    label var level   "Aggregation level: C campus, D district"
    label var dataset "TEA dataset code"

    quietly save "`BUILD'/`ds'_`lv'_`yr'.dta", replace
    local ++nimported
    di as txt "  `ds'_`lv'_`yr'   " %7.0fc _N " obs x " c(k) " vars"
}
di as txt _n "imported `nimported' files"

* ---------------------------------------------------------------------------
* 3. Attach TEA's own label text, where TEA supplied any.
*    Only the wizard route (SY 2024-25) ships labels in the file. Legacy years
*    ship none at all, which is the central problem for the crosswalk: the
*    label history has to come from TEA's per-year glossary PDFs, not the data.
* ---------------------------------------------------------------------------
import delimited using "`STAGE'/labels.csv", varnames(1) case(lower) ///
    stringcols(_all) clear
quietly destring year position, replace
quietly count if tea_label != ""
local NLAB = r(N)
quietly count
di as txt _n "label rows staged: " %9.0fc r(N) "   with TEA label text: " %9.0fc `NLAB'
quietly levelsof year if tea_label != "", local(labyears)
di as txt "years carrying label text: `labyears'"
tempfile labs
save `labs'

* ---------------------------------------------------------------------------
* 4. CROSS-TIME DATA DICTIONARY, files mode.
*    Each wave file is a wave; datadictionary writes one row per variable per
*    wave and flags variables whose label or category set moved.
* ---------------------------------------------------------------------------
di as txt _n "{hline 78}"
di as txt "CROSS-TIME DATA DICTIONARY"
di as txt "{hline 78}"

foreach spec in "REF D" "PROF D" {
    local ds : word 1 of `spec'
    local lv : word 2 of `spec'

    local files ""
    local waves ""
    forvalues y = 2013/2025 {
        capture confirm file "`BUILD'/`ds'_`lv'_`y'.dta"
        if !_rc {
            local files `"`files' "`BUILD'/`ds'_`lv'_`y'.dta""'
            local waves "`waves' `y'"
        }
    }
    if `"`files'"' == "" continue

    di as txt _n "--- `ds' (`lv') waves:`waves' ---"
    capture noisily datadictionary, files(`files') wavenames("`waves'") ///
        excel("`DOCS'/codebook_`ds'_`lv'") saving("`DOCS'/codebook_`ds'_`lv'") replace
    if _rc {
        di as err "  datadictionary failed for `ds' `lv' (rc=" _rc ")"
    }
    else {
        di as res "  codebook rows: " r(nvars) "   changes flagged: " r(nchanges)
    }
}

* ---------------------------------------------------------------------------
* 5. Append REF into a real panel and document it in-memory with wave(year).
*    REF is the only dataset in this subset that spans every year AND is
*    narrow enough to append without harmonising year-embedded names.
* ---------------------------------------------------------------------------
di as txt _n "{hline 78}"
di as txt "APPEND: REF panel"
di as txt "{hline 78}"

clear
tempfile panel
local first 1
foreach lv in C D {
    forvalues y = 2013/2025 {
        capture confirm file "`BUILD'/REF_`lv'_`y'.dta"
        if !_rc {
            if `first' {
                use "`BUILD'/REF_`lv'_`y'.dta", clear
                local first 0
            }
            else {
                append using "`BUILD'/REF_`lv'_`y'.dta"
            }
        }
    }
}
quietly compress
di as txt "REF panel: " %9.0fc _N " rows x " c(k) " vars"
label data "TAPR REF panel, appended across years and levels"
notes _dta: built by build_codebook.do on `c(current_date)'
notes _dta: ccyy is the SPRING year; 2025 = school year 2024-25
quietly save "`BUILD'/ref_panel.dta", replace

* ---- panel key, checked per level -----------------------------------------
*   The key differs by level: a district-year is identified by district, a
*   campus-year by campus. `district year level` is NOT a key, because many
*   campuses share a district in the same year.
di as txt _n "--- panel keys ---"
preserve
    keep if level == "D"
    capture isid district year
    di as txt "  district rows: isid district year -> " ///
        cond(_rc==0, "UNIQUE", "NOT UNIQUE (rc=" + string(_rc) + ")") ///
        "   n = " %9.0fc _N
restore
preserve
    keep if level == "C"
    capture isid campus year
    di as txt "  campus rows:   isid campus year   -> " ///
        cond(_rc==0, "UNIQUE", "NOT UNIQUE (rc=" + string(_rc) + ")") ///
        "   n = " %9.0fc _N

    * the 9-digit campus id should begin with its 6-digit district id; a
    * mismatch means the two identifier columns disagree about who owns a campus
    quietly count if campus != "" & district != "" & substr(campus,1,6) != district
    di as txt "  campus/district id mismatches (substr(campus,1,6) != district): " r(N)
    if r(N) > 0 {
        list year campus district campname if substr(campus,1,6) != district ///
            & campus != "" & district != "" in 1/20, noobs abbrev(16)
    }
restore

* ---- entity churn: the reason a balanced panel would be wrong ---------------
preserve
    keep if level == "D"
    quietly bysort district (year): gen byte nyr = _N
    quietly bysort district (year): egen fy = min(year)
    quietly bysort district (year): egen ly = max(year)
    quietly bysort district (year): keep if _n == 1
    quietly count
    local NDIST = r(N)
    quietly count if nyr == 13
    local NALL = r(N)
    quietly count if (ly - fy + 1) != nyr
    local NGAPD = r(N)
    di as txt _n "--- district churn across 2013-2025 ---"
    di as txt "  distinct districts ever observed: `NDIST'"
    di as txt "  present in all 13 years:          `NALL'"
    di as txt "  present with a GAP (in, out, in): `NGAPD'"
    di as txt "  => an unbalanced panel with first_year/last_year is the honest"
    di as txt "     shape; a balanced one would code 'did not exist' as missing."
restore

di as txt _n "--- datadictionary on the appended panel, wave(year) ---"
capture noisily datadictionary, wave(year) ///
    excel("`DOCS'/codebook_ref_panel") saving("`DOCS'/codebook_ref_panel") replace
if !_rc di as res "  codebook rows: " r(nvars)

* ---------------------------------------------------------------------------
* 6. STRUCTURE AND DRIFT REPORT
*    describe, replace turns variable metadata into data, which is what makes
*    systematic year-to-year diffing possible at all.
* ---------------------------------------------------------------------------
di as txt _n "{hline 78}"
di as txt "DRIFT REPORT"
di as txt "{hline 78}"

clear
tempfile meta
local first 1
forvalues i = 1/`NFILES' {
    use `idx' in `i', clear
    local yr = year
    local lv = level
    local ds = dataset
    capture confirm file "`BUILD'/`ds'_`lv'_`yr'.dta"
    if _rc continue
    use "`BUILD'/`ds'_`lv'_`yr'.dta", clear
    quietly describe, replace
    quietly gen int    year    = `yr'
    quietly gen str1   level   = "`lv'"
    quietly gen str12  dataset = "`ds'"
    if `first' {
        quietly save `meta', replace
        local first 0
    }
    else {
        quietly append using `meta'
        quietly save `meta', replace
    }
}
use `meta', clear
quietly drop if inlist(name, "year", "level", "dataset")
quietly compress
label data "Variable metadata by year x level x dataset"
quietly save "`BUILD'/varmeta.dta", replace
di as txt "metadata rows: " %9.0fc _N

* presence matrix: first and last year each variable appears, and any gap
preserve
    keep if level == "D"
    bysort dataset name (year): gen byte nyears = _N
    bysort dataset name (year): egen first_yr = min(year)
    bysort dataset name (year): egen last_yr  = max(year)
    bysort dataset name (year): keep if _n == 1
    gen byte gap = (last_yr - first_yr + 1) != nyears
    quietly count if gap
    local NGAP = r(N)
    di as txt _n "district-level variables with a GAP in their year run: `NGAP'"
    if `NGAP' > 0 {
        di as txt "  Present, then absent, then present again. In a naive append"
        di as txt "  these become ordinary missing, indistinguishable from a"
        di as txt "  district that simply had no value. Map them to .d instead."
        gen int nmissing = (last_yr - first_yr + 1) - nyears
        list dataset name first_yr last_yr nyears nmissing if gap, ///
            sepby(dataset) noobs abbrev(20)
        drop nmissing
    }
    export delimited using "`DOCS'/variable_presence.csv", replace
restore

* label / type / format drift for variables that persist
*   A storage-type change is only a problem if it crosses the string/numeric
*   boundary. byte -> int -> long is Stata promoting an integer to hold a bigger
*   value, and append handles it silently and correctly. Reporting those as
*   "changes" buries the one kind that actually breaks an append.
preserve
    keep if level == "D"
    gen byte isstr = substr(type, 1, 3) == "str"
    bysort dataset name (year): gen byte labchg = (varlab != varlab[_n-1]) & _n > 1
    bysort dataset name (year): gen byte fmtchg = (format != format[_n-1]) & _n > 1
    bysort dataset name (year): gen byte typechg_break = ///
        (isstr != isstr[_n-1]) & _n > 1
    bysort dataset name (year): gen byte typechg_width = ///
        (type != type[_n-1]) & (isstr == isstr[_n-1]) & _n > 1

    * Split label transitions. A label that goes from text to BLANK is a hole
    * in TEA's dictionary coverage, not a rewording -- TEA publishes no REF
    * dictionary at all for 2016 or 2017. Counting those as "label changed"
    * would put 2 spurious change rows on every REF variable in those years.
    bysort dataset name (year): gen byte lab_missing = ///
        ((varlab == "") != (varlab[_n-1] == "")) & _n > 1
    bysort dataset name (year): gen byte lab_reworded = ///
        labchg & varlab != "" & varlab[_n-1] != ""
    quietly count if labchg
    di as txt _n "label transitions detected: " r(N)
    quietly count if lab_reworded
    di as txt "  genuine rewordings (both years labelled): " r(N)
    quietly count if lab_missing
    di as txt "  artefacts of missing dictionary coverage:  " r(N)
    quietly count if typechg_width
    local NW = r(N)
    quietly count if typechg_break
    di as txt "storage-type changes that BREAK an append (string <-> numeric): " r(N)
    if r(N) > 0 {
        list dataset name year type varlab if typechg_break, ///
            noobs abbrev(18) sepby(dataset)
    }
    di as txt "storage-type changes that are harmless (numeric width only): `NW'"
    quietly count if fmtchg
    di as txt "display-format changes: " r(N)
    export delimited using "`DOCS'/variable_drift.csv", replace
restore

* column-position drift, the trap that makes position-based parsing unsafe
preserve
    keep if level == "D" & dataset == "REF"
    quietly bysort name (year): gen byte posmoved = (position != position[_n-1]) & _n > 1
    quietly count if posmoved
    di as txt _n "REF: column-position moves: " r(N)
    if r(N) > 0 {
        tabdisp name year, cellvar(position) concise
        di as txt "  (this is why the id column must be found by NAME, not position)"
    }
restore

* ---------------------------------------------------------------------------
* 6b. HOW MUCH DOES THE STEM RULE ACTUALLY BUY?
*     TAPR embeds the two-digit year in the variable name just before the
*     trailing N/D/R, so the same measure is called dpetgifc one year and
*     something else the next. Stripping that year gives a "stem" that should be
*     stable. This measures how far that gets us, per dataset, instead of
*     assuming it solves everything.
* ---------------------------------------------------------------------------
di as txt _n "{hline 78}"
di as txt "STEM RULE EFFECTIVENESS"
di as txt "{hline 78}"
preserve
    use "`BUILD'/varmeta.dta", clear
    keep if level == "D"
    gen str40 stem = regexr(name, "([0-9][0-9])([ndrNDR])$", "@\\2")
    gen byte parsed = stem != name

    * one row per dataset x name, then per dataset x stem; no nested preserve
    bysort dataset name: keep if _n == 1
    by dataset: egen long n_names  = count(name)
    by dataset: egen long n_parsed = total(parsed)
    bysort dataset stem: gen byte firststem = _n == 1
    by dataset: egen long n_stems = total(firststem)
    bysort dataset: keep if _n == 1
    keep dataset n_names n_stems n_parsed
    gen double pct_parsed   = 100 * n_parsed / n_names
    gen double pct_collapse = 100 * (n_names - n_stems) / n_names
    format pct_* %5.1f
    list dataset n_names n_stems pct_parsed pct_collapse, noobs abbrev(14) sep(0)
    export delimited using "`DOCS'/stem_rule.csv", replace

    di as txt _n "  pct_parsed   = share of names carrying a year in the expected position"
    di as txt "  pct_collapse = share of distinct names absorbed into a shared stem"
    di as txt "  A high collapse means the year-in-name is the main source of"
    di as txt "  apparent churn and the stem rule handles it. A low one means that"
    di as txt "  dataset genuinely changes content year to year and needs a"
    di as txt "  hand-maintained crosswalk on top."
restore

* ---- label coverage, so gaps are visible rather than silently distorting ----
di as txt _n "--- label coverage by year (district level) ---"
preserve
    use "`BUILD'/varmeta.dta", clear
    keep if level == "D"
    gen byte haslab = varlab != ""
    collapse (sum) labelled=haslab (count) nvars=haslab, by(dataset year)
    gen double pct = 100 * labelled / nvars
    format pct %5.0f
    quietly levelsof dataset, local(dl)
    foreach d of local dl {
        di as txt _n "  `d':"
        list year nvars labelled pct if dataset == "`d'", noobs sep(0) abbrev(10)
    }
    quietly count if pct < 50
    if r(N) > 0 {
        di as err _n "  `r(N)' dataset-years have under 50% label coverage."
        di as err "  Label changes reported into or out of those years are"
        di as err "  coverage artefacts, not rewordings."
    }
    export delimited using "`DOCS'/label_coverage.csv", replace
restore

* value-label drift, which describe cannot see
di as txt _n "--- labelbook on the appended REF panel ---"
use "`BUILD'/ref_panel.dta", clear
quietly labelbook
capture noisily labelbook, problems

di as txt _n "{hline 78}"
di as txt "OUTPUTS"
di as txt "{hline 78}"
di as txt "  `DOCS'/codebook_REF_D.xlsx        cross-time, change-flagged"
di as txt "  `DOCS'/codebook_PROF_D.xlsx       cross-time, change-flagged"
di as txt "  `DOCS'/codebook_ref_panel.xlsx    appended panel, wave(year)"
di as txt "  `DOCS'/variable_presence.csv      first/last year, gaps"
di as txt "  `DOCS'/variable_drift.csv         label/type/format changes"
di as txt "  `BUILD'/ref_panel.dta             the appended panel"
di as txt "  `BUILD'/varmeta.dta               metadata by year x level x dataset"

log close
